#!/bin/bash
# MIT License
# 
# Copyright (c) 2017 Roger Light.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

if [ "$1" == "-b" ]; then MODE="-c"; shift; else MODE="-n"; fi
if [ "$#" != "3" ]; then
	echo "apphollow hollows out a file and saves it as a new file."
	echo "Choose how many lines/bytes to remove from the middle of the file."
	printf "Default behaviour removes lines, use -b to count by bytes instead.\n\n"
	echo "Usage: apphollow [-b] count input-file output-file"
	exit;
fi
if [ ! -f $2 ]; then echo "File \"$2\" not found."; exit; fi
if [ "$MODE" == "-c" ]; then
	SZ=$(/bin/ls -l $2 | awk '{print $5}')
else
	SZ=$(wc -l $2 | awk '{print $1}')
fi
if [[ -n ${1//[0-9]/} ]]; then echo "Count not a number."; exit; fi
if [ $1 -le 0 -o $1 -ge $SZ ]; then echo "Count <0 or bigger than file size."; exit; fi
let TRIMSZ=($SZ-$1)/2
head $MODE $TRIMSZ -q $2 > $3
tail $MODE $TRIMSZ -q $2 >> $3
